---

- hosts: localhost
  any_errors_fatal: true 
  connection: local
  tasks:

   - include_vars: vars/info_vars1.yml

   - name: Reading User CSV file
     read_csv:
       path: vars/userinput.yml
     register: user_list
     delegate_to: localhost
     tags:
     - always

   - name: Displaying what to get change
     debug:
       var: user_list.list
     tags:
     - always

   - name: Running A record creation role
     include_role:
       name: create_a_record
     loop: "{{ user_list.list }}"
     tags:
     - create


   - name: Running A record deletion role
     include_role:
       name: delete_a_record
     loop: "{{ user_list.list }}"
     tags:
     - delete
